// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fCU5dsWyQZcddYeLiZDEIB5ll2RWoeU',
    appId: '1:256848572479:web:3dfbfa9abb5d4dfeaf888a',
    messagingSenderId: '256848572479',
    projectId: 'duraes-bc9c7',
    authDomain: 'duraes-bc9c7.firebaseapp.com',
    storageBucket: 'duraes-bc9c7.appspot.com',
    measurementId: 'G-EHYTWJHRHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9imzYLIX4XQ1YiSCC0hKNDZGS0MrvJCg',
    appId: '1:256848572479:android:dcc9a05ba44ed6d7af888a',
    messagingSenderId: '256848572479',
    projectId: 'duraes-bc9c7',
    storageBucket: 'duraes-bc9c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJhVjvLOQiNV-60fqYQ-Jj7rl1I8nPNgc',
    appId: '1:256848572479:ios:49e3f5a30dd6eb29af888a',
    messagingSenderId: '256848572479',
    projectId: 'duraes-bc9c7',
    storageBucket: 'duraes-bc9c7.appspot.com',
    iosClientId: '256848572479-38jlsjecm9c9rsl4h9i4oihpr0c2qmnc.apps.googleusercontent.com',
    iosBundleId: 'br.com.aceleradordeecommerce.duraes',
  );
}
